apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2019-07-03T03:42:12Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author: {}
    branch: master
    committer: {}
    message: |
      upgrade jenkins-x/jx-ts-client client to jx 2.0.392
    sha: df325fd9a79d542ef4865591a4cff8a36bf02681
  gitCloneUrl: https://github.com/jenkins-x/jx.git
  gitHttpUrl: https://github.com/jenkins-x/jx
  gitOwner: jenkins-x
  gitRepository: jx
  name: '{{ .Chart.Name }}'
  version: 2.0.393
status: {}
