apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2019-07-03T00:44:09Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author: {}
    branch: master
    committer: {}
    message: |
      chore: set default values for external-dns during jx boot

      Signed-off-by: rawlingsj <rawlingsj80@gmail.com>
    sha: 6a6513bafe218669a9b5c4a7cb94b30283b35d19
  gitCloneUrl: https://github.com/jenkins-x/jx.git
  gitHttpUrl: https://github.com/jenkins-x/jx
  gitOwner: jenkins-x
  gitRepository: jx
  name: '{{ .Chart.Name }}'
  version: 2.0.390
status: {}
