apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2019-07-02T19:58:14Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author: {}
    branch: master
    committer: {}
    message: |
      fix(tekton): Add a random suffix to Tekton CRD name base to avoid duplication

      Signed-off-by: Andrew Bayer <andrew.bayer@gmail.com>
    sha: 11278b3169cc30bbf52e12e8ec646f6b18d4f1f4
  gitCloneUrl: https://github.com/jenkins-x/jx.git
  gitHttpUrl: https://github.com/jenkins-x/jx
  gitOwner: jenkins-x
  gitRepository: jx
  name: '{{ .Chart.Name }}'
  version: 2.0.387
status: {}
