apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2019-07-02T14:32:26Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author: {}
    branch: master
    committer: {}
    message: |
      fix: specify the repo in updatebot
    sha: bd4b0f6f9c8f57498454bedfdaf71bfa3847701c
  gitCloneUrl: https://github.com/jenkins-x/jx.git
  gitHttpUrl: https://github.com/jenkins-x/jx
  gitOwner: jenkins-x
  gitRepository: jx
  name: '{{ .Chart.Name }}'
  version: 2.0.383
status: {}
